# Generated by Django 6.1.1 on 2026-09-19 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='course',
            field=models.CharField(max_length=100),
        ),
    ]
