# Generated by Django 6.1.1 on 2026-09-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_student_data_address_alter_student_data_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='middle_name',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
