# Generated by Django 6.1.1 on 2026-09-19 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_course_alter_student_data_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.course'),
        ),
    ]
